PresentationApplication/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationApplication.Models
{
    public class Invoice
    {
        public int InvoiceID { get; set; }
        public string Number { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}

PresentationApplication/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PresentationApplication.Models;
using PresentationApplication.DAL;
using PresentationApplication.Data;
using PresentationApplication.Helper;

namespace PresentationApplication.Controllers
{
    public class InvoicesController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public InvoicesController(IUnitOfWork unitOfWork)
        {
           _unitOfWork = unitOfWork;
        }
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Invoices
        public ActionResult Index()
        {
            return View(_unitOfWork.Invoices.GetAll());
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = _unitOfWork.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            InvoiceViewModel viewModel = new InvoiceViewModel();
            return View(viewModel);
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AjaxValidateAntiForgeryToken]
        public JsonResult Create(InvoiceViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Invoices.Add(viewModel.Invoice);
                _unitOfWork.SaveChanges();
                return Json(true);
            }

            return Json(false);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = _unitOfWork.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceID,Number")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Invoices.Edit(invoice);
                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = _unitOfWork.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = _unitOfWork.Invoices.Find(id);
            _unitOfWork.Invoices.Delete(invoice);
            _unitOfWork.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PresentationApplication/Views/Invoices/Create.cshtml
@model PresentationApplication.DAL.InvoiceViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

    @Html.AntiForgeryToken()
    <form id="itemForm">
        <table class="table table-responsive">
            <tr>
                <th class="col-sm-2">
                    Nazwa
                </th>
                <th></th>
            </tr>
            <tr class="form-group-sm" id="MainRow">
                <td class="col-sm-2">
                    @Html.EditorFor(model => model.Item.Name, new { htmlAttributes = new { @class = "itemName form-control" } })
                    @Html.ValidationMessageFor(model => model.Item.Name, "", new { @class = "text-danger error" })
                </td>
                <td class="col-sm-2"></td>
                <td>
                    <input type="button" value="Dodaj" class="btn btn-success" id="Add" />

                </td>
            </tr>


        </table>
    </form>
    <div id="invoiceItems">
        <table class="table table-responsive" id="InvoiceDetailsItems"></table>
        <span id="InvoiceItemError" style="color:red"></span>
    </div>

    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Invoice.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Invoice.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Invoice.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="SaveInvoice" />
            </div>
        </div>
    </div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#Add').click(function () {
                    var $newRow = $('#MainRow').clone().removeAttr('id');
                    $('#Add', $newRow).addClass('remove').val('Usuń').removeAttr('id').removeClass('btn-success').addClass('btn-danger');
                    $('#Item_Name', $newRow).each(
                        function () {
                            $(this).attr("id", generateUUID());

                        });

                    $('span.error', $newRow).remove();
                    $('#InvoiceDetailsItems').append($newRow);
                    $('#InvoiceItemError').empty('');
                
            });
            $('#InvoiceDetailsItems').on('click', '.remove', function () {
                $(this).parents('tr').remove();
            });
            $("#SaveInvoice").click(function () {
                var invoiceItemLength = document.getElementById("InvoiceDetailsItems").children.length + 1;
                var invoiceItemList = [];
                if(invoiceItemLength==0){
                    return;
                }
                for (var i = 1; i < invoiceItemLength; i++) {
                    var invoiceItem = {
                        Name: document.getElementsByClassName("itemName")[i].value,
                    };
                    invoiceItemList.push(invoiceItem);
                }
                invoiceData = {
                    Number: document.getElementById("Invoice_Number").value,
                    Items: invoiceItemList

                };
                data = {
                    Invoice: invoiceData
                }
                $.ajax({
                    type: 'Post',
                    url: '/Invoices/Create',
                    data: JSON.stringify(data),
                    headers: {
                        'VerificationToken': $("#forgeryToken").val()
                    },
                    contentType: 'application/json',
                    success: function (success) {
                        if (success) {
                            window.location.replace("@Html.Encode(Url.Action("Index", "Invoices"))");
                        }

                    },
                    error: function (error) {
                        console.log(error);
                    }

                });

            });
        });
    </script>
}

PresentationApplication/Views/Invoices/Delete.cshtml
@model PresentationApplication.Models.Invoice

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PresentationApplication/Views/Invoices/Details.cshtml
@model PresentationApplication.Models.Invoice

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.InvoiceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PresentationApplication/Views/Invoices/Edit.cshtml
@model PresentationApplication.Models.Invoice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InvoiceID)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PresentationApplication/Views/Invoices/Index.cshtml
@model IEnumerable<PresentationApplication.Models.Invoice>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.InvoiceID }) |
            @Html.ActionLink("Details", "Details", new { id=item.InvoiceID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.InvoiceID })
        </td>
    </tr>
}

</table>